// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemperatureMonitor.Application.Database;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220522091457_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TemperatureMonitor.Application.Database.Entities.СottageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Сottages");
                });

            modelBuilder.Entity("TemperatureMonitor.Application.Database.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleEntity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a6246a17-3a9a-447b-9c33-0ab5f675fe59"),
                            Name = "admin"
                        },
                        new
                        {
                            Id = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            Name = "person"
                        });
                });

            modelBuilder.Entity("TemperatureMonitor.Application.Database.Entities.SensorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("TemperatureMonitor.Application.Database.Entities.SensorTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("SensorTypes");
                });

            modelBuilder.Entity("TemperatureMonitor.Application.Database.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2efd74fb-e7d5-4d18-86c0-fa77600ba76d"),
                            Name = "admin",
                            Password = "admin"
                        },
                        new
                        {
                            Id = new Guid("48633b8c-73a4-4d5c-b86e-7149eb31b2c2"),
                            FirstName = "First name 1",
                            LastName = "Last name",
                            Name = "person1",
                            Password = "person1"
                        },
                        new
                        {
                            Id = new Guid("274d0a64-9627-47d0-b671-7f7ae3b6a55c"),
                            FirstName = "First name 2",
                            LastName = "Last name",
                            Name = "person2",
                            Password = "person2"
                        },
                        new
                        {
                            Id = new Guid("8e91287d-1b50-445e-bfa7-c18e311fd828"),
                            FirstName = "First name 3",
                            LastName = "Last name",
                            Name = "person3",
                            Password = "person3"
                        },
                        new
                        {
                            Id = new Guid("f51baf9b-9c23-4706-8cf5-6c37d5e9a13d"),
                            FirstName = "First name 4",
                            LastName = "Last name",
                            Name = "person4",
                            Password = "person4"
                        },
                        new
                        {
                            Id = new Guid("db601f12-2abf-4ff5-8727-7e8cf26c9666"),
                            FirstName = "First name 5",
                            LastName = "Last name",
                            Name = "person5",
                            Password = "person5"
                        },
                        new
                        {
                            Id = new Guid("bb520cd4-f09d-4021-aa81-ba9d0762062a"),
                            FirstName = "First name 6",
                            LastName = "Last name",
                            Name = "person6",
                            Password = "person6"
                        },
                        new
                        {
                            Id = new Guid("f0dd1dfd-db2a-4293-8ae0-c1b9b93f3bf1"),
                            FirstName = "First name 7",
                            LastName = "Last name",
                            Name = "person7",
                            Password = "person7"
                        },
                        new
                        {
                            Id = new Guid("90e30517-60af-4d4b-bd54-8166b6a00017"),
                            FirstName = "First name 8",
                            LastName = "Last name",
                            Name = "person8",
                            Password = "person8"
                        },
                        new
                        {
                            Id = new Guid("1f7fb911-c33f-40e3-8a2f-60bae37449e1"),
                            FirstName = "First name 9",
                            LastName = "Last name",
                            Name = "person9",
                            Password = "person9"
                        },
                        new
                        {
                            Id = new Guid("b9362601-3f2d-405a-ae98-423d96917a6e"),
                            FirstName = "First name 10",
                            LastName = "Last name",
                            Name = "person10",
                            Password = "person10"
                        },
                        new
                        {
                            Id = new Guid("171d4f92-2827-4a25-bf6a-59100309867e"),
                            FirstName = "First name 11",
                            LastName = "Last name",
                            Name = "person11",
                            Password = "person11"
                        },
                        new
                        {
                            Id = new Guid("f33fe090-f3ab-4b84-9bd0-411f8fa45894"),
                            FirstName = "First name 12",
                            LastName = "Last name",
                            Name = "person12",
                            Password = "person12"
                        },
                        new
                        {
                            Id = new Guid("8eb2ad8e-9b63-477d-90ac-4b1a6b759ad4"),
                            FirstName = "First name 13",
                            LastName = "Last name",
                            Name = "person13",
                            Password = "person13"
                        },
                        new
                        {
                            Id = new Guid("a321c8f0-e324-40d4-a05a-e4b97b6c3060"),
                            FirstName = "First name 14",
                            LastName = "Last name",
                            Name = "person14",
                            Password = "person14"
                        },
                        new
                        {
                            Id = new Guid("307fcb6a-d491-44cf-9318-5cd7095052ac"),
                            FirstName = "First name 15",
                            LastName = "Last name",
                            Name = "person15",
                            Password = "person15"
                        },
                        new
                        {
                            Id = new Guid("e337f5c1-67ad-478f-8cf8-36bbe8e096d9"),
                            FirstName = "First name 16",
                            LastName = "Last name",
                            Name = "person16",
                            Password = "person16"
                        },
                        new
                        {
                            Id = new Guid("6ef9efb7-2515-4fb2-89ae-aad56c8c5c1c"),
                            FirstName = "First name 17",
                            LastName = "Last name",
                            Name = "person17",
                            Password = "person17"
                        },
                        new
                        {
                            Id = new Guid("0f5ddd09-e2b6-428b-88f6-17364cae4ccf"),
                            FirstName = "First name 18",
                            LastName = "Last name",
                            Name = "person18",
                            Password = "person18"
                        },
                        new
                        {
                            Id = new Guid("8c051532-4b47-4344-b2be-e70261778f71"),
                            FirstName = "First name 19",
                            LastName = "Last name",
                            Name = "person19",
                            Password = "person19"
                        },
                        new
                        {
                            Id = new Guid("0b3482cc-d278-41a3-b5bf-a4831ad971e9"),
                            FirstName = "First name 20",
                            LastName = "Last name",
                            Name = "person20",
                            Password = "person20"
                        },
                        new
                        {
                            Id = new Guid("87602d81-989c-4985-9850-2e52f30b154f"),
                            FirstName = "First name 21",
                            LastName = "Last name",
                            Name = "person21",
                            Password = "person21"
                        },
                        new
                        {
                            Id = new Guid("fd3581e8-9a3a-4d8d-b115-fad8e9e60613"),
                            FirstName = "First name 22",
                            LastName = "Last name",
                            Name = "person22",
                            Password = "person22"
                        },
                        new
                        {
                            Id = new Guid("15405ef4-d151-4ee9-83d0-e7e20606440f"),
                            FirstName = "First name 23",
                            LastName = "Last name",
                            Name = "person23",
                            Password = "person23"
                        },
                        new
                        {
                            Id = new Guid("dd0af4fd-8d01-466c-a9ca-3bd23139b2d0"),
                            FirstName = "First name 24",
                            LastName = "Last name",
                            Name = "person24",
                            Password = "person24"
                        },
                        new
                        {
                            Id = new Guid("6381e5a1-0404-4862-9f65-a3f8615ce3d3"),
                            FirstName = "First name 25",
                            LastName = "Last name",
                            Name = "person25",
                            Password = "person25"
                        },
                        new
                        {
                            Id = new Guid("c21891eb-5841-40ef-9a0b-6b276e24661b"),
                            FirstName = "First name 26",
                            LastName = "Last name",
                            Name = "person26",
                            Password = "person26"
                        },
                        new
                        {
                            Id = new Guid("0556b11a-7e36-432e-9d4e-5b5966ea0aa7"),
                            FirstName = "First name 27",
                            LastName = "Last name",
                            Name = "person27",
                            Password = "person27"
                        },
                        new
                        {
                            Id = new Guid("56f41414-9a58-4d26-867f-2e709286d0a9"),
                            FirstName = "First name 28",
                            LastName = "Last name",
                            Name = "person28",
                            Password = "person28"
                        },
                        new
                        {
                            Id = new Guid("5277dcf1-1414-49a6-b7c1-22533e214baf"),
                            FirstName = "First name 29",
                            LastName = "Last name",
                            Name = "person29",
                            Password = "person29"
                        },
                        new
                        {
                            Id = new Guid("837ee3d3-ced2-4d6f-a555-e2920e960a77"),
                            FirstName = "First name 30",
                            LastName = "Last name",
                            Name = "person30",
                            Password = "person30"
                        },
                        new
                        {
                            Id = new Guid("2fcf5865-69da-4fb4-a9f9-a6890499fdf1"),
                            FirstName = "First name 31",
                            LastName = "Last name",
                            Name = "person31",
                            Password = "person31"
                        },
                        new
                        {
                            Id = new Guid("16419431-30d1-40c8-bd79-24f5bf96f38f"),
                            FirstName = "First name 32",
                            LastName = "Last name",
                            Name = "person32",
                            Password = "person32"
                        },
                        new
                        {
                            Id = new Guid("d0784e39-b445-4001-b4ff-8426234a558a"),
                            FirstName = "First name 33",
                            LastName = "Last name",
                            Name = "person33",
                            Password = "person33"
                        },
                        new
                        {
                            Id = new Guid("af89229e-4d2d-4402-9e39-ac21f29804b6"),
                            FirstName = "First name 34",
                            LastName = "Last name",
                            Name = "person34",
                            Password = "person34"
                        },
                        new
                        {
                            Id = new Guid("d994d069-fe36-4708-b098-e8b3552ab414"),
                            FirstName = "First name 35",
                            LastName = "Last name",
                            Name = "person35",
                            Password = "person35"
                        },
                        new
                        {
                            Id = new Guid("fe9264e1-5827-4675-b366-de5b1a750a1b"),
                            FirstName = "First name 36",
                            LastName = "Last name",
                            Name = "person36",
                            Password = "person36"
                        },
                        new
                        {
                            Id = new Guid("c010ca62-bbe8-42a2-9f4b-87f2c72f5184"),
                            FirstName = "First name 37",
                            LastName = "Last name",
                            Name = "person37",
                            Password = "person37"
                        },
                        new
                        {
                            Id = new Guid("92ff1108-561c-478f-b1d2-dd0e48acf2c6"),
                            FirstName = "First name 38",
                            LastName = "Last name",
                            Name = "person38",
                            Password = "person38"
                        },
                        new
                        {
                            Id = new Guid("edd55fa0-10cf-4b1b-b746-f3c2708e3ec5"),
                            FirstName = "First name 39",
                            LastName = "Last name",
                            Name = "person39",
                            Password = "person39"
                        },
                        new
                        {
                            Id = new Guid("f2e0fdd3-b90a-4906-b382-b69f88bf8206"),
                            FirstName = "First name 40",
                            LastName = "Last name",
                            Name = "person40",
                            Password = "person40"
                        },
                        new
                        {
                            Id = new Guid("aa5de081-cf9b-46e2-9238-23474003c011"),
                            FirstName = "First name 41",
                            LastName = "Last name",
                            Name = "person41",
                            Password = "person41"
                        },
                        new
                        {
                            Id = new Guid("6f3b8b5b-feb4-4380-87b3-caf109f2c51b"),
                            FirstName = "First name 42",
                            LastName = "Last name",
                            Name = "person42",
                            Password = "person42"
                        },
                        new
                        {
                            Id = new Guid("130da61d-dee5-4584-96ff-6b7803ace3ae"),
                            FirstName = "First name 43",
                            LastName = "Last name",
                            Name = "person43",
                            Password = "person43"
                        },
                        new
                        {
                            Id = new Guid("f0b0c073-c409-43a4-b1f9-e777a90695cc"),
                            FirstName = "First name 44",
                            LastName = "Last name",
                            Name = "person44",
                            Password = "person44"
                        },
                        new
                        {
                            Id = new Guid("7119af9b-93e5-49fb-8870-29c6ff787e85"),
                            FirstName = "First name 45",
                            LastName = "Last name",
                            Name = "person45",
                            Password = "person45"
                        },
                        new
                        {
                            Id = new Guid("c5d7dc24-d80d-498c-8c41-7a7062948651"),
                            FirstName = "First name 46",
                            LastName = "Last name",
                            Name = "person46",
                            Password = "person46"
                        },
                        new
                        {
                            Id = new Guid("cb2606a2-8f78-46d2-8dc6-f229d654527d"),
                            FirstName = "First name 47",
                            LastName = "Last name",
                            Name = "person47",
                            Password = "person47"
                        },
                        new
                        {
                            Id = new Guid("24c4fd20-3cf2-46f6-8f09-1f8018aabfa9"),
                            FirstName = "First name 48",
                            LastName = "Last name",
                            Name = "person48",
                            Password = "person48"
                        },
                        new
                        {
                            Id = new Guid("6a722c6c-a404-42cb-adb4-b704d329a29a"),
                            FirstName = "First name 49",
                            LastName = "Last name",
                            Name = "person49",
                            Password = "person49"
                        },
                        new
                        {
                            Id = new Guid("c68969b3-92c3-4107-b2a6-d3c73cd87afa"),
                            FirstName = "First name 50",
                            LastName = "Last name",
                            Name = "person50",
                            Password = "person50"
                        },
                        new
                        {
                            Id = new Guid("2bfb5113-39b6-47f9-8395-4e22fc1138a5"),
                            FirstName = "First name 51",
                            LastName = "Last name",
                            Name = "person51",
                            Password = "person51"
                        },
                        new
                        {
                            Id = new Guid("dd3b6d71-0a7f-48fb-83d1-2b40638005ed"),
                            FirstName = "First name 52",
                            LastName = "Last name",
                            Name = "person52",
                            Password = "person52"
                        },
                        new
                        {
                            Id = new Guid("25f6bddd-f3f9-4a60-ae23-969fb47e8bbc"),
                            FirstName = "First name 53",
                            LastName = "Last name",
                            Name = "person53",
                            Password = "person53"
                        },
                        new
                        {
                            Id = new Guid("174b95ed-c6fd-4ee4-8b32-1ea6c0e0d5b9"),
                            FirstName = "First name 54",
                            LastName = "Last name",
                            Name = "person54",
                            Password = "person54"
                        },
                        new
                        {
                            Id = new Guid("556eb268-2299-46da-b597-b3ab43f442b0"),
                            FirstName = "First name 55",
                            LastName = "Last name",
                            Name = "person55",
                            Password = "person55"
                        },
                        new
                        {
                            Id = new Guid("26d647e9-1cf9-42c9-9ab5-fefec84fccc7"),
                            FirstName = "First name 56",
                            LastName = "Last name",
                            Name = "person56",
                            Password = "person56"
                        },
                        new
                        {
                            Id = new Guid("d8bb8bff-65ac-4a49-942e-0ca69c39bc94"),
                            FirstName = "First name 57",
                            LastName = "Last name",
                            Name = "person57",
                            Password = "person57"
                        },
                        new
                        {
                            Id = new Guid("edaae3d0-4288-4490-9920-fb1cec2fc934"),
                            FirstName = "First name 58",
                            LastName = "Last name",
                            Name = "person58",
                            Password = "person58"
                        },
                        new
                        {
                            Id = new Guid("a88a4665-0418-41f1-bde7-e1045c58d98c"),
                            FirstName = "First name 59",
                            LastName = "Last name",
                            Name = "person59",
                            Password = "person59"
                        },
                        new
                        {
                            Id = new Guid("2681412e-e0ff-4bad-8856-7e8c04fde8d6"),
                            FirstName = "First name 60",
                            LastName = "Last name",
                            Name = "person60",
                            Password = "person60"
                        },
                        new
                        {
                            Id = new Guid("a5793da8-abfd-4aa1-aeaa-65d04531428f"),
                            FirstName = "First name 61",
                            LastName = "Last name",
                            Name = "person61",
                            Password = "person61"
                        },
                        new
                        {
                            Id = new Guid("eeaff2d5-a18b-4a57-b5a9-3b268a51d72c"),
                            FirstName = "First name 62",
                            LastName = "Last name",
                            Name = "person62",
                            Password = "person62"
                        },
                        new
                        {
                            Id = new Guid("e00c21cd-4e69-49ee-b4d3-39ed16edb72f"),
                            FirstName = "First name 63",
                            LastName = "Last name",
                            Name = "person63",
                            Password = "person63"
                        },
                        new
                        {
                            Id = new Guid("2c32dd7c-8112-4f45-99b9-01e5ae5eef6f"),
                            FirstName = "First name 64",
                            LastName = "Last name",
                            Name = "person64",
                            Password = "person64"
                        },
                        new
                        {
                            Id = new Guid("a03fe766-5976-469f-884f-a725609adede"),
                            FirstName = "First name 65",
                            LastName = "Last name",
                            Name = "person65",
                            Password = "person65"
                        },
                        new
                        {
                            Id = new Guid("05473a76-9a09-490f-8e70-20814d951290"),
                            FirstName = "First name 66",
                            LastName = "Last name",
                            Name = "person66",
                            Password = "person66"
                        },
                        new
                        {
                            Id = new Guid("e3340851-09fc-46cb-8064-cb2986cc7b0e"),
                            FirstName = "First name 67",
                            LastName = "Last name",
                            Name = "person67",
                            Password = "person67"
                        },
                        new
                        {
                            Id = new Guid("7de654fb-af59-4279-b300-051e17055555"),
                            FirstName = "First name 68",
                            LastName = "Last name",
                            Name = "person68",
                            Password = "person68"
                        },
                        new
                        {
                            Id = new Guid("2b6d1417-9f95-43b9-981c-1ec4d3c65bf1"),
                            FirstName = "First name 69",
                            LastName = "Last name",
                            Name = "person69",
                            Password = "person69"
                        },
                        new
                        {
                            Id = new Guid("f48895c5-6459-4970-8eb4-b7dbaa397f3d"),
                            FirstName = "First name 70",
                            LastName = "Last name",
                            Name = "person70",
                            Password = "person70"
                        },
                        new
                        {
                            Id = new Guid("38e5638f-07d0-4142-a7ef-ce9958dbf927"),
                            FirstName = "First name 71",
                            LastName = "Last name",
                            Name = "person71",
                            Password = "person71"
                        },
                        new
                        {
                            Id = new Guid("16a55a72-229f-4fc4-a309-08f0f9c8cbc1"),
                            FirstName = "First name 72",
                            LastName = "Last name",
                            Name = "person72",
                            Password = "person72"
                        },
                        new
                        {
                            Id = new Guid("fd435d92-9c40-41a0-8bd0-c7f6f6236ebd"),
                            FirstName = "First name 73",
                            LastName = "Last name",
                            Name = "person73",
                            Password = "person73"
                        },
                        new
                        {
                            Id = new Guid("1019d3f0-8650-4aa7-a311-03cb3c8eef86"),
                            FirstName = "First name 74",
                            LastName = "Last name",
                            Name = "person74",
                            Password = "person74"
                        },
                        new
                        {
                            Id = new Guid("06730fcb-1517-4984-86c1-fac42f3cd1e0"),
                            FirstName = "First name 75",
                            LastName = "Last name",
                            Name = "person75",
                            Password = "person75"
                        },
                        new
                        {
                            Id = new Guid("09376356-9f8c-4188-a379-da6156c1e303"),
                            FirstName = "First name 76",
                            LastName = "Last name",
                            Name = "person76",
                            Password = "person76"
                        },
                        new
                        {
                            Id = new Guid("93f820d1-66ed-4e75-8907-3649be63de6e"),
                            FirstName = "First name 77",
                            LastName = "Last name",
                            Name = "person77",
                            Password = "person77"
                        },
                        new
                        {
                            Id = new Guid("83df782d-5e2b-4aed-947c-f5d7bd124ded"),
                            FirstName = "First name 78",
                            LastName = "Last name",
                            Name = "person78",
                            Password = "person78"
                        },
                        new
                        {
                            Id = new Guid("52e4a79b-f5bf-4889-8d6b-5f96778115b5"),
                            FirstName = "First name 79",
                            LastName = "Last name",
                            Name = "person79",
                            Password = "person79"
                        },
                        new
                        {
                            Id = new Guid("de51267b-4b91-410f-b897-b4b19f8bed63"),
                            FirstName = "First name 80",
                            LastName = "Last name",
                            Name = "person80",
                            Password = "person80"
                        },
                        new
                        {
                            Id = new Guid("7e2929b7-c8b3-445a-ba0e-cbd1f57eef81"),
                            FirstName = "First name 81",
                            LastName = "Last name",
                            Name = "person81",
                            Password = "person81"
                        },
                        new
                        {
                            Id = new Guid("50473396-40b2-4362-9f6c-b4888f8f878a"),
                            FirstName = "First name 82",
                            LastName = "Last name",
                            Name = "person82",
                            Password = "person82"
                        },
                        new
                        {
                            Id = new Guid("611f0c5e-4b56-4797-872c-4209a07493f4"),
                            FirstName = "First name 83",
                            LastName = "Last name",
                            Name = "person83",
                            Password = "person83"
                        },
                        new
                        {
                            Id = new Guid("51ab2064-0dcd-4d82-8a28-48885fb3dbd5"),
                            FirstName = "First name 84",
                            LastName = "Last name",
                            Name = "person84",
                            Password = "person84"
                        },
                        new
                        {
                            Id = new Guid("994207df-9173-482d-b1e0-f75de959328f"),
                            FirstName = "First name 85",
                            LastName = "Last name",
                            Name = "person85",
                            Password = "person85"
                        },
                        new
                        {
                            Id = new Guid("e5b4032c-05d6-42cc-8e7f-7cd04e182ae4"),
                            FirstName = "First name 86",
                            LastName = "Last name",
                            Name = "person86",
                            Password = "person86"
                        },
                        new
                        {
                            Id = new Guid("fd0c5457-588a-4840-91e9-7f8d4c959288"),
                            FirstName = "First name 87",
                            LastName = "Last name",
                            Name = "person87",
                            Password = "person87"
                        },
                        new
                        {
                            Id = new Guid("7208d4f6-a299-4435-9ae8-ddb81e4e6551"),
                            FirstName = "First name 88",
                            LastName = "Last name",
                            Name = "person88",
                            Password = "person88"
                        },
                        new
                        {
                            Id = new Guid("6812304d-f5b2-45ea-b3e2-d505af72d1c4"),
                            FirstName = "First name 89",
                            LastName = "Last name",
                            Name = "person89",
                            Password = "person89"
                        },
                        new
                        {
                            Id = new Guid("f8edad64-b38f-46cd-a212-f4c6ebb647b3"),
                            FirstName = "First name 90",
                            LastName = "Last name",
                            Name = "person90",
                            Password = "person90"
                        },
                        new
                        {
                            Id = new Guid("be34d684-62e5-4839-ab47-5c42812df591"),
                            FirstName = "First name 91",
                            LastName = "Last name",
                            Name = "person91",
                            Password = "person91"
                        },
                        new
                        {
                            Id = new Guid("010953d8-9263-4e81-8d31-9aa68574a73e"),
                            FirstName = "First name 92",
                            LastName = "Last name",
                            Name = "person92",
                            Password = "person92"
                        },
                        new
                        {
                            Id = new Guid("9a7db461-5cc7-4c14-afac-11c5cc1a3bc9"),
                            FirstName = "First name 93",
                            LastName = "Last name",
                            Name = "person93",
                            Password = "person93"
                        },
                        new
                        {
                            Id = new Guid("c8761bea-bb1b-4a8a-afa6-a360a3bd8b48"),
                            FirstName = "First name 94",
                            LastName = "Last name",
                            Name = "person94",
                            Password = "person94"
                        },
                        new
                        {
                            Id = new Guid("f7b0dfc1-383a-4c3e-aafe-fd453eda8d0d"),
                            FirstName = "First name 95",
                            LastName = "Last name",
                            Name = "person95",
                            Password = "person95"
                        },
                        new
                        {
                            Id = new Guid("7e7d049a-ae40-4179-8ce3-99bef396095f"),
                            FirstName = "First name 96",
                            LastName = "Last name",
                            Name = "person96",
                            Password = "person96"
                        },
                        new
                        {
                            Id = new Guid("ea1039ef-1070-4c2c-9356-5fe1dce73617"),
                            FirstName = "First name 97",
                            LastName = "Last name",
                            Name = "person97",
                            Password = "person97"
                        },
                        new
                        {
                            Id = new Guid("c1219f3d-bc69-47f3-9d61-a288cea4af57"),
                            FirstName = "First name 98",
                            LastName = "Last name",
                            Name = "person98",
                            Password = "person98"
                        },
                        new
                        {
                            Id = new Guid("420aba1f-8646-4f5a-b5a9-c9f4f1147666"),
                            FirstName = "First name 99",
                            LastName = "Last name",
                            Name = "person99",
                            Password = "person99"
                        },
                        new
                        {
                            Id = new Guid("2c30d9fd-7490-4f4f-9ddf-83ad478f7d04"),
                            FirstName = "First name 100",
                            LastName = "Last name",
                            Name = "person100",
                            Password = "person100"
                        });
                });

            modelBuilder.Entity("TemperatureMonitor.Application.Database.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fffb99b5-76c9-4014-8f1d-3dbf615634d9"),
                            RoleId = new Guid("a6246a17-3a9a-447b-9c33-0ab5f675fe59"),
                            UserId = new Guid("2efd74fb-e7d5-4d18-86c0-fa77600ba76d")
                        },
                        new
                        {
                            Id = new Guid("fe41800b-a475-4ebb-90d7-073fa74a4afc"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("48633b8c-73a4-4d5c-b86e-7149eb31b2c2")
                        },
                        new
                        {
                            Id = new Guid("605be9e4-ef92-480b-b65e-bf4a09199d87"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("274d0a64-9627-47d0-b671-7f7ae3b6a55c")
                        },
                        new
                        {
                            Id = new Guid("08fc8ae1-a2a3-463f-9340-64f1d13d8bec"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("8e91287d-1b50-445e-bfa7-c18e311fd828")
                        },
                        new
                        {
                            Id = new Guid("25031a45-2104-4aec-8ee9-1b75acc452e2"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("f51baf9b-9c23-4706-8cf5-6c37d5e9a13d")
                        },
                        new
                        {
                            Id = new Guid("34f7b0a1-60e1-4b2e-9a25-5e94a1dae1ca"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("db601f12-2abf-4ff5-8727-7e8cf26c9666")
                        },
                        new
                        {
                            Id = new Guid("da3ee545-c2fa-48cf-b054-07b03436f876"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("bb520cd4-f09d-4021-aa81-ba9d0762062a")
                        },
                        new
                        {
                            Id = new Guid("c3fd79d7-fc4e-4b84-bd57-92df8147b892"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("f0dd1dfd-db2a-4293-8ae0-c1b9b93f3bf1")
                        },
                        new
                        {
                            Id = new Guid("ca7e42e7-c0af-4e0e-9d8a-ac10c12b6926"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("90e30517-60af-4d4b-bd54-8166b6a00017")
                        },
                        new
                        {
                            Id = new Guid("60afe861-190f-4021-974d-249b08186bbf"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("1f7fb911-c33f-40e3-8a2f-60bae37449e1")
                        },
                        new
                        {
                            Id = new Guid("cd136272-ad27-492c-939d-e4d108945877"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("b9362601-3f2d-405a-ae98-423d96917a6e")
                        },
                        new
                        {
                            Id = new Guid("2593d58a-9986-439c-b91b-29829ec21c6d"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("171d4f92-2827-4a25-bf6a-59100309867e")
                        },
                        new
                        {
                            Id = new Guid("e8f17446-eeb0-4f8d-8845-d11d45a7d1c5"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("f33fe090-f3ab-4b84-9bd0-411f8fa45894")
                        },
                        new
                        {
                            Id = new Guid("53852a35-47b8-4b02-bb59-ebedff6aa23b"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("8eb2ad8e-9b63-477d-90ac-4b1a6b759ad4")
                        },
                        new
                        {
                            Id = new Guid("d0f8764f-0c36-4aac-8a82-2b127cbd0df3"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("a321c8f0-e324-40d4-a05a-e4b97b6c3060")
                        },
                        new
                        {
                            Id = new Guid("08764e32-5e84-4a4e-84d5-667626fd6d36"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("307fcb6a-d491-44cf-9318-5cd7095052ac")
                        },
                        new
                        {
                            Id = new Guid("467f59d1-cdd5-494d-b402-1520bbeb7530"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("e337f5c1-67ad-478f-8cf8-36bbe8e096d9")
                        },
                        new
                        {
                            Id = new Guid("129f50f8-d07b-43f6-b991-417976420b41"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("6ef9efb7-2515-4fb2-89ae-aad56c8c5c1c")
                        },
                        new
                        {
                            Id = new Guid("7e364767-a05f-4317-8de4-b06055168065"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("0f5ddd09-e2b6-428b-88f6-17364cae4ccf")
                        },
                        new
                        {
                            Id = new Guid("e43f19b7-46c4-4338-9bde-d1c54b3cf220"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("8c051532-4b47-4344-b2be-e70261778f71")
                        },
                        new
                        {
                            Id = new Guid("07d62031-62b4-4f7f-bc92-64cf78a7d226"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("0b3482cc-d278-41a3-b5bf-a4831ad971e9")
                        },
                        new
                        {
                            Id = new Guid("03d7c278-e277-4c83-a040-aa785aac3def"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("87602d81-989c-4985-9850-2e52f30b154f")
                        },
                        new
                        {
                            Id = new Guid("c3fab6a2-0d33-4cce-9f34-8ad2cccddee6"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("fd3581e8-9a3a-4d8d-b115-fad8e9e60613")
                        },
                        new
                        {
                            Id = new Guid("36b2bb28-a1ea-46f7-9851-dfc58baf72bf"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("15405ef4-d151-4ee9-83d0-e7e20606440f")
                        },
                        new
                        {
                            Id = new Guid("09782946-113e-4907-a18b-0416367d8122"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("dd0af4fd-8d01-466c-a9ca-3bd23139b2d0")
                        },
                        new
                        {
                            Id = new Guid("0e525041-9b87-487f-b5ec-7eeb4cfc31d7"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("6381e5a1-0404-4862-9f65-a3f8615ce3d3")
                        },
                        new
                        {
                            Id = new Guid("8b1e57f9-e95b-4625-8b1b-389c1da478da"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("c21891eb-5841-40ef-9a0b-6b276e24661b")
                        },
                        new
                        {
                            Id = new Guid("9dceaf3e-5f1f-42ef-af99-2d95199b0699"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("0556b11a-7e36-432e-9d4e-5b5966ea0aa7")
                        },
                        new
                        {
                            Id = new Guid("8413955c-5672-48ec-b90b-9092da76a754"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("56f41414-9a58-4d26-867f-2e709286d0a9")
                        },
                        new
                        {
                            Id = new Guid("d4655eb9-bfba-4b04-8237-cd68bdbedffb"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("5277dcf1-1414-49a6-b7c1-22533e214baf")
                        },
                        new
                        {
                            Id = new Guid("fdb7ce6d-50b9-406a-a6a6-64d8a9cd0703"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("837ee3d3-ced2-4d6f-a555-e2920e960a77")
                        },
                        new
                        {
                            Id = new Guid("45f2d9cb-39e6-4971-b503-f6b5b6bac0dc"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("2fcf5865-69da-4fb4-a9f9-a6890499fdf1")
                        },
                        new
                        {
                            Id = new Guid("d443c5e5-9707-4698-a4f9-e6b1b80ecb95"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("16419431-30d1-40c8-bd79-24f5bf96f38f")
                        },
                        new
                        {
                            Id = new Guid("8af571f5-45e8-4a00-b8fe-7a6b6f1de02e"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("d0784e39-b445-4001-b4ff-8426234a558a")
                        },
                        new
                        {
                            Id = new Guid("09df816c-91a8-41cd-ad56-45a9b14bbb9c"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("af89229e-4d2d-4402-9e39-ac21f29804b6")
                        },
                        new
                        {
                            Id = new Guid("d33dbe32-a398-4a6c-9fdf-9a41d0dd35f8"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("d994d069-fe36-4708-b098-e8b3552ab414")
                        },
                        new
                        {
                            Id = new Guid("d34bea6a-f014-41e7-845e-da7b15908fb5"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("fe9264e1-5827-4675-b366-de5b1a750a1b")
                        },
                        new
                        {
                            Id = new Guid("44f34959-0730-4130-aca6-d89d5e71938e"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("c010ca62-bbe8-42a2-9f4b-87f2c72f5184")
                        },
                        new
                        {
                            Id = new Guid("cd0118d8-c9b3-4edf-aca4-eece46863cbd"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("92ff1108-561c-478f-b1d2-dd0e48acf2c6")
                        },
                        new
                        {
                            Id = new Guid("f6c664ac-4877-4905-98b5-1e6d07fb7d9e"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("edd55fa0-10cf-4b1b-b746-f3c2708e3ec5")
                        },
                        new
                        {
                            Id = new Guid("2bc94ff4-2d7d-4495-98a9-c63ddc5e9f8e"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("f2e0fdd3-b90a-4906-b382-b69f88bf8206")
                        },
                        new
                        {
                            Id = new Guid("d957db73-8cc9-4bdb-9e50-c5e7a2c83424"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("aa5de081-cf9b-46e2-9238-23474003c011")
                        },
                        new
                        {
                            Id = new Guid("3f5e2a9c-68b4-4b95-8f28-c8e218c0c9c2"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("6f3b8b5b-feb4-4380-87b3-caf109f2c51b")
                        },
                        new
                        {
                            Id = new Guid("e1f3e97c-5847-4439-84e1-9fb3a220067c"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("130da61d-dee5-4584-96ff-6b7803ace3ae")
                        },
                        new
                        {
                            Id = new Guid("44abd783-0165-4b71-a7df-342609be1d03"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("f0b0c073-c409-43a4-b1f9-e777a90695cc")
                        },
                        new
                        {
                            Id = new Guid("18ff980b-6ab4-49c0-95bf-b07bb6e2c81b"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("7119af9b-93e5-49fb-8870-29c6ff787e85")
                        },
                        new
                        {
                            Id = new Guid("90e0c35f-b5ea-46bb-8d18-0c8008d1370f"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("c5d7dc24-d80d-498c-8c41-7a7062948651")
                        },
                        new
                        {
                            Id = new Guid("5f701313-905d-430a-8416-dd82be8a8ade"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("cb2606a2-8f78-46d2-8dc6-f229d654527d")
                        },
                        new
                        {
                            Id = new Guid("a514dd2b-1fa8-469f-a039-87680acab0f6"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("24c4fd20-3cf2-46f6-8f09-1f8018aabfa9")
                        },
                        new
                        {
                            Id = new Guid("002d0320-532a-4815-9554-e4da2499236e"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("6a722c6c-a404-42cb-adb4-b704d329a29a")
                        },
                        new
                        {
                            Id = new Guid("61e69b7e-b5fd-445a-bba0-be0b41a509e7"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("c68969b3-92c3-4107-b2a6-d3c73cd87afa")
                        },
                        new
                        {
                            Id = new Guid("f5af144b-1a8f-457a-90a0-e5bce3ac0080"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("2bfb5113-39b6-47f9-8395-4e22fc1138a5")
                        },
                        new
                        {
                            Id = new Guid("bb17d2fe-b7ee-406e-96ff-c74a0e0c6bb7"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("dd3b6d71-0a7f-48fb-83d1-2b40638005ed")
                        },
                        new
                        {
                            Id = new Guid("ac3a0c4a-93c7-4ad1-8b14-ba9e954a94c3"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("25f6bddd-f3f9-4a60-ae23-969fb47e8bbc")
                        },
                        new
                        {
                            Id = new Guid("b948ce7c-576b-44ea-b2ab-099f44c66387"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("174b95ed-c6fd-4ee4-8b32-1ea6c0e0d5b9")
                        },
                        new
                        {
                            Id = new Guid("c7ea2415-184a-46a2-af7c-48526398dd99"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("556eb268-2299-46da-b597-b3ab43f442b0")
                        },
                        new
                        {
                            Id = new Guid("8ad3f7b0-da1f-4c8b-af3a-9f5d8518eb6d"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("26d647e9-1cf9-42c9-9ab5-fefec84fccc7")
                        },
                        new
                        {
                            Id = new Guid("59b9d8ce-5ca0-46a4-b577-5e4bc265d947"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("d8bb8bff-65ac-4a49-942e-0ca69c39bc94")
                        },
                        new
                        {
                            Id = new Guid("71a785e2-a862-45ae-b445-6d3568bc216c"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("edaae3d0-4288-4490-9920-fb1cec2fc934")
                        },
                        new
                        {
                            Id = new Guid("475e05a3-6b45-42f1-8317-044ce94698e0"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("a88a4665-0418-41f1-bde7-e1045c58d98c")
                        },
                        new
                        {
                            Id = new Guid("2bd60941-818c-4540-8e9a-5a32db46a014"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("2681412e-e0ff-4bad-8856-7e8c04fde8d6")
                        },
                        new
                        {
                            Id = new Guid("d44dfe91-133d-4869-afcc-342540c6af45"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("a5793da8-abfd-4aa1-aeaa-65d04531428f")
                        },
                        new
                        {
                            Id = new Guid("be3e8b12-11ae-4d0f-a817-3a483487f64d"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("eeaff2d5-a18b-4a57-b5a9-3b268a51d72c")
                        },
                        new
                        {
                            Id = new Guid("85f8a367-1c16-4ae9-a219-5c042c52eee8"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("e00c21cd-4e69-49ee-b4d3-39ed16edb72f")
                        },
                        new
                        {
                            Id = new Guid("82b1236a-2cfd-47c8-8dae-e748fd570d59"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("2c32dd7c-8112-4f45-99b9-01e5ae5eef6f")
                        },
                        new
                        {
                            Id = new Guid("d870d304-9aee-45cd-8b0b-5a3f2d619e55"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("a03fe766-5976-469f-884f-a725609adede")
                        },
                        new
                        {
                            Id = new Guid("18cfa534-d055-4c5f-873d-9364fc41fe3e"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("05473a76-9a09-490f-8e70-20814d951290")
                        },
                        new
                        {
                            Id = new Guid("cd0cb5b8-24f9-43ba-8441-e08a016c3d8c"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("e3340851-09fc-46cb-8064-cb2986cc7b0e")
                        },
                        new
                        {
                            Id = new Guid("39aa3d26-f09c-4795-8f73-5d88d29d8aad"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("7de654fb-af59-4279-b300-051e17055555")
                        },
                        new
                        {
                            Id = new Guid("4a8ffd03-fd17-4f9d-9cfa-cf3664cf2f23"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("2b6d1417-9f95-43b9-981c-1ec4d3c65bf1")
                        },
                        new
                        {
                            Id = new Guid("cc392152-6902-47c8-8442-1c3e2d31aac2"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("f48895c5-6459-4970-8eb4-b7dbaa397f3d")
                        },
                        new
                        {
                            Id = new Guid("b5e03e3a-a3a6-4e09-9a77-636b803415b7"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("38e5638f-07d0-4142-a7ef-ce9958dbf927")
                        },
                        new
                        {
                            Id = new Guid("0908e9f9-27fe-4dad-b63c-3f9963fadac2"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("16a55a72-229f-4fc4-a309-08f0f9c8cbc1")
                        },
                        new
                        {
                            Id = new Guid("64b5c538-cfc1-4eb0-b3a5-1d96cf417eae"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("fd435d92-9c40-41a0-8bd0-c7f6f6236ebd")
                        },
                        new
                        {
                            Id = new Guid("f8aec5c5-e470-4ca1-a254-6381c14fad68"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("1019d3f0-8650-4aa7-a311-03cb3c8eef86")
                        },
                        new
                        {
                            Id = new Guid("f252aba1-cb64-49b0-a570-080181bd41cc"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("06730fcb-1517-4984-86c1-fac42f3cd1e0")
                        },
                        new
                        {
                            Id = new Guid("f22a1496-4612-4554-a7d0-504431ed2bba"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("09376356-9f8c-4188-a379-da6156c1e303")
                        },
                        new
                        {
                            Id = new Guid("0abe4546-5e38-4cf8-807b-b7ebf477970e"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("93f820d1-66ed-4e75-8907-3649be63de6e")
                        },
                        new
                        {
                            Id = new Guid("f3f0b1e7-d935-4c67-8e43-0663302fafef"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("83df782d-5e2b-4aed-947c-f5d7bd124ded")
                        },
                        new
                        {
                            Id = new Guid("982c1643-c6db-4f21-9c23-244c97e36d91"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("52e4a79b-f5bf-4889-8d6b-5f96778115b5")
                        },
                        new
                        {
                            Id = new Guid("ffb1c486-0b21-4447-a9d2-e1a68c3568e5"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("de51267b-4b91-410f-b897-b4b19f8bed63")
                        },
                        new
                        {
                            Id = new Guid("a1c91278-0c6a-4248-bb5c-1749f0b735fd"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("7e2929b7-c8b3-445a-ba0e-cbd1f57eef81")
                        },
                        new
                        {
                            Id = new Guid("fe54ad36-418d-448c-904d-fec5518b49dd"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("50473396-40b2-4362-9f6c-b4888f8f878a")
                        },
                        new
                        {
                            Id = new Guid("c5dc856a-bf6d-4e14-b606-0417602f1858"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("611f0c5e-4b56-4797-872c-4209a07493f4")
                        },
                        new
                        {
                            Id = new Guid("fe51858d-dee5-47f0-9c9f-1bcadbaea48d"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("51ab2064-0dcd-4d82-8a28-48885fb3dbd5")
                        },
                        new
                        {
                            Id = new Guid("6c0db608-4979-46cf-a468-fd9e28256ae4"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("994207df-9173-482d-b1e0-f75de959328f")
                        },
                        new
                        {
                            Id = new Guid("4b22c3aa-1f4a-4870-b354-e903a8aa6ed4"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("e5b4032c-05d6-42cc-8e7f-7cd04e182ae4")
                        },
                        new
                        {
                            Id = new Guid("59150efe-00c1-4c72-8fdd-0d9d39da56e1"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("fd0c5457-588a-4840-91e9-7f8d4c959288")
                        },
                        new
                        {
                            Id = new Guid("6bf7bf93-8757-4d07-b2be-7999c0466c7e"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("7208d4f6-a299-4435-9ae8-ddb81e4e6551")
                        },
                        new
                        {
                            Id = new Guid("0a5c9cd3-ec66-448d-a8f6-9678112616c2"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("6812304d-f5b2-45ea-b3e2-d505af72d1c4")
                        },
                        new
                        {
                            Id = new Guid("3aede10e-8e49-47e5-a525-fd70a41bae5d"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("f8edad64-b38f-46cd-a212-f4c6ebb647b3")
                        },
                        new
                        {
                            Id = new Guid("4ce2b701-cb67-48f4-b935-faf184e2c8bd"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("be34d684-62e5-4839-ab47-5c42812df591")
                        },
                        new
                        {
                            Id = new Guid("90fcbe0b-d5c4-4ff6-843d-7bea8a1d7cd7"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("010953d8-9263-4e81-8d31-9aa68574a73e")
                        },
                        new
                        {
                            Id = new Guid("22687a4c-97fe-4abc-96bf-165330698717"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("9a7db461-5cc7-4c14-afac-11c5cc1a3bc9")
                        },
                        new
                        {
                            Id = new Guid("19f1159c-529d-41b1-bd29-8d856e9b60f0"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("c8761bea-bb1b-4a8a-afa6-a360a3bd8b48")
                        },
                        new
                        {
                            Id = new Guid("f11ad8f2-21ed-4256-b26f-ab0c9dbc4720"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("f7b0dfc1-383a-4c3e-aafe-fd453eda8d0d")
                        },
                        new
                        {
                            Id = new Guid("a539e702-bb83-4478-8c8d-5d2f795556b0"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("7e7d049a-ae40-4179-8ce3-99bef396095f")
                        },
                        new
                        {
                            Id = new Guid("9f8cd987-e096-4de9-9088-cb35fd9524c0"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("ea1039ef-1070-4c2c-9356-5fe1dce73617")
                        },
                        new
                        {
                            Id = new Guid("4c991ca8-656a-4ab5-951d-385a20791150"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("c1219f3d-bc69-47f3-9d61-a288cea4af57")
                        },
                        new
                        {
                            Id = new Guid("a367d9c1-b21e-4fcb-a619-ae8e4cb4ba70"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("420aba1f-8646-4f5a-b5a9-c9f4f1147666")
                        },
                        new
                        {
                            Id = new Guid("12d9c171-3d18-4e9c-b513-75926504c5c0"),
                            RoleId = new Guid("b150872b-cbe4-4e79-8a99-e6d202ddf588"),
                            UserId = new Guid("2c30d9fd-7490-4f4f-9ddf-83ad478f7d04")
                        });
                });

            modelBuilder.Entity("TemperatureMonitor.Application.Database.Entities.SensorTypeEntity", b =>
                {
                    b.HasOne("TemperatureMonitor.Application.Database.Entities.SensorEntity", "User")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TemperatureMonitor.Application.Database.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("TemperatureMonitor.Application.Database.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TemperatureMonitor.Application.Database.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TemperatureMonitor.Application.Database.Entities.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TemperatureMonitor.Application.Database.Entities.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
